sudo: required

language: cpp

services:
  - docker

install: skip

script:
  - echo "skipping tests"
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker pull ${DOCKER_USERNAME}/val3dity:latest || true
  - docker build . --cache-from ${DOCKER_USERNAME}/val3dity:latest -t ${DOCKER_USERNAME}/val3dity:latest


deploy:
  - provider: script
    script: docker push ${DOCKER_USERNAME}/val3dity:latest
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: docker tag ${DOCKER_USERNAME}/val3dity:latest ${DOCKER_USERNAME}/val3dity:dev ; docker push ${DOCKER_USERNAME}/val3dity:dev
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: docker tag ${DOCKER_USERNAME}/val3dity:latest ${DOCKER_USERNAME}/val3dity:${TRAVIS_TAG} ; docker push ${DOCKER_USERNAME}/val3dity:${TRAVIS_TAG}
    skip_cleanup: true
    on:
      tags: true
