os: linux

language: cpp

services:
  - docker

install: skip

script:
  - echo "skipping tests"
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker pull tudelft3d/val3dity:latest || true
  - docker build . --cache-from tudelft3d/val3dity:latest -t tudelft3d/val3dity:latest


deploy:
  - provider: script
    script: docker push tudelft3d/val3dity:latest
    cleanup: false
    on:
      branch: master
  - provider: script
    script: docker tag tudelft3d/val3dity:latest tudelft3d/val3dity:dev ; docker push tudelft3d/val3dity:dev
    cleanup: false
    on:
      branch: develop
  - provider: script
    script: docker tag tudelft3d/val3dity:latest tudelft3d/val3dity:${TRAVIS_TAG} ; docker push tudelft3d/val3dity:${TRAVIS_TAG}
    cleanup: false
    on:
      tags: true
